default_platform(:ios)

platform :ios do
  lane :build do
    gym(
      scheme: "Airbuddies",
      project: "./Airbuddies.xcodeproj",
      configuration: "Release",
      output_directory: ".",
      output_name: "Airbuddies",
      export_method: "ad-hoc",
      xcargs: "-allowProvisioningUpdates"
    )
  end
end
